sonar.projectKey=VannaDii_tsoa-next
sonar.organization=vannadii
sonar.projectName=tsoa-next
sonar.host.url=https://sonarcloud.io

sonar.sources=packages/cli/src,packages/runtime/src,packages/tsoa/src
sonar.tests=tests,tests/esm

sonar.exclusions=**/*.d.ts,**/dist/**,**/fixtures/**,coverage/**,site/**
sonar.test.inclusions=tests/**/*.spec.ts,tests/esm/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
