sonar.projectKey=tsoa-next_tsoa-next
sonar.organization=tsoa-next
sonar.projectName=tsoa-next
sonar.host.url=https://sonarcloud.io

sonar.sources=packages/cli/src,packages/runtime/src,packages/tsoa/src
sonar.tests=tests

sonar.exclusions=**/*.d.ts,**/dist/**,**/fixtures/**,coverage/**,site/**
sonar.test.inclusions=tests/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
