export * from './module/generate-spec'
export * from './module/generate-routes'
export { AbstractRouteGenerator } from './routeGeneration/routeGenerator'
export { DefaultRouteGenerator } from './routeGeneration/defaultRouteGenerator'
export { Config } from '@tsoa-next/runtime'
export { generateSpecAndRoutes, validateCompilerOptions, validateRoutesConfig, validateSpecConfig } from './api'
export type { ConfigArgs, ExtendedRoutesConfig, ExtendedSpecConfig, RouteGeneratorModule, SwaggerArgs } from './api'
export { runCLI } from './runCLI'
