name: Welcome first time contributors

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello there ${{ github.actor }} 👋

            Thank you for opening your very first issue in this project. 

            We will try to get back to you as soon as we can.👀

          pr-message: |
            Hello there ${{ github.actor }} 👋

            Thank you and congrats 🎉 for opening your first PR on this project.✨

            We will review the following PR soon! 👀
